name: Cypress

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Cypress (pipeline)
        run: npm run cypress:pipeRun
        env:
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME }}
          CYPRESS_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          CYPRESS_ADMIN_USER_NAME: ${{ secrets.ADMIN_USER_NAME }}
          CYPRESS_ADMIN_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
          CYPRESS_ADMIN_USER_PASSWORD: ${{ secrets.ADMIN_USER_PASSWORD }}
